version: '3'
services:
  # sonarqube:
  #   image: sonarqube:9.8.0-community
  #   ports:
  #     - '9001:9000'
  #   environment:
  #     - SONAR_JDBC_URL=jdbc:postgresql://database:5432/sonarqube
  #     - SONAR_JDBC_USERNAME=sonarqube
  #     - SONAR_JDBC_PASSWORD=sonarqube
  #     - SONAR_JAVA_OPTS=-Dsonar.java.source=17 -Dsonar.java.target=17
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions

  database:
    image: mysql
    container_name: mysql-container
    command: --authentication_policy=CACHING_SHA2_PASSWORD
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: eccomerceRootPwd
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes: 
      - ./api/db/data:/var/lib/mysql
    restart: always

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


volumes:
  sonarqube_data:
  sonarqube_extensions:
  postgres_data: